name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm i
      - run: npm run prepare
      - run: npm run build
      - run: npm publish
        env:
          GH_TOKEN: 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
          NPM_TOKEN: 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
